# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: v*
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      #- name: Docker login
      #  env:
      #    DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      #    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}  
      #  run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
      
      - name: docker login & build & push
        env:
          GITHUB_REF: ${{ github.ref }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}  
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo GITHUB_REF - $ref
          echo ${DOCKER_HUB_TOKEN} | docker login -u ${DOCKER_LOGIN} --password-stdin
          docker build \
          -t ${DOCKER_LOGIN}/doxod-bot:${ref} \
          -t ${DOCKER_LOGIN}/doxod-bot:latest .
          docker push -t ${DOCKER_LOGIN}/doxod-bot:${ref} 
          docker push -t ${DOCKER_LOGIN}/doxod-bot:latest
